# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/aboose/Desktop/Fall Semester WSU 2024-25/Cpt_S 121/PAs/Boose_PA6"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/aboose/Desktop/Fall Semester WSU 2024-25/Cpt_S 121/PAs/Boose_PA6"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/aboose/Desktop/Fall Semester WSU 2024-25/Cpt_S 121/PAs/Boose_PA6/CMakeFiles" "/Users/aboose/Desktop/Fall Semester WSU 2024-25/Cpt_S 121/PAs/Boose_PA6//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/aboose/Desktop/Fall Semester WSU 2024-25/Cpt_S 121/PAs/Boose_PA6/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Boose_PA6

# Build rule for target.
Boose_PA6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boose_PA6
.PHONY : Boose_PA6

# fast build rule for target.
Boose_PA6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/build
.PHONY : Boose_PA6/fast

src/board.o: src/board.c.o
.PHONY : src/board.o

# target to build an object file
src/board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/board.c.o
.PHONY : src/board.c.o

src/board.i: src/board.c.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/board.c.i
.PHONY : src/board.c.i

src/board.s: src/board.c.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/board.c.s
.PHONY : src/board.c.s

src/ctty/keypress.o: src/ctty/keypress.c.o
.PHONY : src/ctty/keypress.o

# target to build an object file
src/ctty/keypress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keypress.c.o
.PHONY : src/ctty/keypress.c.o

src/ctty/keypress.i: src/ctty/keypress.c.i
.PHONY : src/ctty/keypress.i

# target to preprocess a source file
src/ctty/keypress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keypress.c.i
.PHONY : src/ctty/keypress.c.i

src/ctty/keypress.s: src/ctty/keypress.c.s
.PHONY : src/ctty/keypress.s

# target to generate assembly for a file
src/ctty/keypress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keypress.c.s
.PHONY : src/ctty/keypress.c.s

src/ctty/keyselect.o: src/ctty/keyselect.c.o
.PHONY : src/ctty/keyselect.o

# target to build an object file
src/ctty/keyselect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keyselect.c.o
.PHONY : src/ctty/keyselect.c.o

src/ctty/keyselect.i: src/ctty/keyselect.c.i
.PHONY : src/ctty/keyselect.i

# target to preprocess a source file
src/ctty/keyselect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keyselect.c.i
.PHONY : src/ctty/keyselect.c.i

src/ctty/keyselect.s: src/ctty/keyselect.c.s
.PHONY : src/ctty/keyselect.s

# target to generate assembly for a file
src/ctty/keyselect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/ctty/keyselect.c.s
.PHONY : src/ctty/keyselect.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boose_PA6.dir/build.make CMakeFiles/Boose_PA6.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Boose_PA6"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/ctty/keypress.o"
	@echo "... src/ctty/keypress.i"
	@echo "... src/ctty/keypress.s"
	@echo "... src/ctty/keyselect.o"
	@echo "... src/ctty/keyselect.i"
	@echo "... src/ctty/keyselect.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

